CREATE USER c##ferremas IDENTIFIED BY ferremas2;
GRANT CREATE SESSION TO c##ferremas;
GRANT CREATE SESSION, CREATE TABLE, CREATE SEQUENCE, ALTER SESSION TO c##ferremas;
GRANT SELECT, INSERT, UPDATE, DELETE TO c##ferremas;
ALTER USER c##ferremas QUOTA UNLIMITED ON USERS;


GRANT CREATE ANY DIRECTORY TO ferremas2;
CREATE DIRECTORY DIR_FOTOS_PRODUCTOS AS 'C:\imagenes';
GRANT READ, WRITE ON DIRECTORY DIR_FOTOS_PRODUCTOS TO ferremas2;
